# encoding: utf-8
#

title "InSpec Profile: generated by Iggy v0.4.0"
control "aws_ec2_instance::i-0e96d06d9c9ba8b27" do
  title "InSpec-Iggy aws_ec2_instance::i-0e96d06d9c9ba8b27"
  desc  "
    aws_ec2_instance::i-0e96d06d9c9ba8b27 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_ec2_instance("i-0e96d06d9c9ba8b27") do
    it { should exist }
    its("id") { should eq "i-0e96d06d9c9ba8b27" }
    its("instance_type") { should eq "t2.medium" }
    its("key_name") { should eq "dbright-key" }
    its("subnet_id") { should eq "subnet-f9cb13a5" }
  end
end

control "aws_ec2_instance::i-010dc94d4e43791aa" do
  title "InSpec-Iggy aws_ec2_instance::i-010dc94d4e43791aa"
  desc  "
    aws_ec2_instance::i-010dc94d4e43791aa from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_ec2_instance("i-010dc94d4e43791aa") do
    it { should exist }
    its("id") { should eq "i-010dc94d4e43791aa" }
    its("instance_type") { should eq "t2.medium" }
    its("key_name") { should eq "dbright-key" }
    its("subnet_id") { should eq "subnet-f9cb13a5" }
  end
end

control "aws_ec2_instance::i-08d18321146fe8794" do
  title "InSpec-Iggy aws_ec2_instance::i-08d18321146fe8794"
  desc  "
    aws_ec2_instance::i-08d18321146fe8794 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_ec2_instance("i-08d18321146fe8794") do
    it { should exist }
    its("id") { should eq "i-08d18321146fe8794" }
    its("instance_type") { should eq "t2.medium" }
    its("key_name") { should eq "dbright-key" }
    its("subnet_id") { should eq "subnet-f9cb13a5" }
  end
end

control "aws_ec2_instance::i-08c1de87d62caaa50" do
  title "InSpec-Iggy aws_ec2_instance::i-08c1de87d62caaa50"
  desc  "
    aws_ec2_instance::i-08c1de87d62caaa50 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_ec2_instance("i-08c1de87d62caaa50") do
    it { should exist }
    its("id") { should eq "i-08c1de87d62caaa50" }
    its("instance_type") { should eq "t2.medium" }
    its("key_name") { should eq "dbright-key" }
    its("subnet_id") { should eq "subnet-f9cb13a5" }
  end
end

control "aws_route_table::rtb-b80fd1c7" do
  title "InSpec-Iggy aws_route_table::rtb-b80fd1c7"
  desc  "
    aws_route_table::rtb-b80fd1c7 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_route_table("rtb-b80fd1c7") do
    it { should exist }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_route_table::rtb-9b1dc3e4" do
  title "InSpec-Iggy aws_route_table::rtb-9b1dc3e4"
  desc  "
    aws_route_table::rtb-9b1dc3e4 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_route_table("rtb-9b1dc3e4") do
    it { should exist }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_route_table::rtb-630ad41c" do
  title "InSpec-Iggy aws_route_table::rtb-630ad41c"
  desc  "
    aws_route_table::rtb-630ad41c from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_route_table("rtb-630ad41c") do
    it { should exist }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_s3_bucket::dbright-tfstate-bucket" do
  title "InSpec-Iggy aws_s3_bucket::dbright-tfstate-bucket"
  desc  "
    aws_s3_bucket::dbright-tfstate-bucket from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_s3_bucket("dbright-tfstate-bucket") do
    it { should exist }
    its("region") { should eq "us-east-1" }
  end
end

control "aws_security_group::sg-de34b395" do
  title "InSpec-Iggy aws_security_group::sg-de34b395"
  desc  "
    aws_security_group::sg-de34b395 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_security_group("sg-de34b395") do
    it { should exist }
    its("description") { should eq "Allow inbound SSH traffic to Admin VPC from allowed IPs" }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_security_group::sg-8d2cabc6" do
  title "InSpec-Iggy aws_security_group::sg-8d2cabc6"
  desc  "
    aws_security_group::sg-8d2cabc6 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_security_group("sg-8d2cabc6") do
    it { should exist }
    its("description") { should eq "Allow all inbound traffic to the Internal VPC from Admin SG and SELF SG" }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_subnet::subnet-e7be6580" do
  title "InSpec-Iggy aws_subnet::subnet-e7be6580"
  desc  "
    aws_subnet::subnet-e7be6580 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_subnet("subnet-e7be6580") do
    it { should exist }
    its("availability_zone") { should eq "us-east-1b" }
    its("cidr_block") { should eq "10.12.12.32/27" }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_subnet::subnet-451dc76b" do
  title "InSpec-Iggy aws_subnet::subnet-451dc76b"
  desc  "
    aws_subnet::subnet-451dc76b from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_subnet("subnet-451dc76b") do
    it { should exist }
    its("availability_zone") { should eq "us-east-1c" }
    its("cidr_block") { should eq "10.12.12.64/27" }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_subnet::subnet-f9cb13a5" do
  title "InSpec-Iggy aws_subnet::subnet-f9cb13a5"
  desc  "
    aws_subnet::subnet-f9cb13a5 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_subnet("subnet-f9cb13a5") do
    it { should exist }
    its("availability_zone") { should eq "us-east-1a" }
    its("cidr_block") { should eq "10.12.12.0/27" }
    its("vpc_id") { should eq "vpc-6b8d6c11" }
  end
end

control "aws_vpc::vpc-6b8d6c11" do
  title "InSpec-Iggy aws_vpc::vpc-6b8d6c11"
  desc  "
    aws_vpc::vpc-6b8d6c11 from the source file /Users/dbright/gdrive/git-repos/terraform-chef-test-env/aws/terraform.tfstate.backup
    Generated by InSpec-Iggy v0.4.0
  "
  impact 1.0
  describe aws_vpc("vpc-6b8d6c11") do
    it { should exist }
    its("cidr_block") { should eq "10.12.12.0/24" }
    its("dhcp_options_id") { should eq "dopt-f8a24c9d" }
    its("instance_tenancy") { should eq "default" }
  end
end